## 0. Importação de bibliotecas

In [ ]:
import pandas as pd
import numpy as np

## 1. Coleta dos dados

Dados relativos ao resultado da prova ENEM 2019 do estado de São Paulo

In [ ]:
data_file_path = "/content/drive/MyDrive/Portfolio - Data Analysis | BI/Databases/enem_sp_2019/microdados_enem_2019_sp.csv"

In [ ]:
df = pd.read_csv(data_file_path, sep=";", encoding="ISO-8859-1")

In [ ]:
df.shape

(813772, 44)

In [ ]:
# Definindo visualização de colunas no pandas como ilimitado
pd.set_option('display.max_columns', None)

In [ ]:
df.head(5)

,NU_INSCRICAO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_NASCIMENTO,NO_MUNICIPIO_NASCIMENTO,CO_UF_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",3546801,Santa Isabel,35,SP,22,M,1,3,1,1506500.0,Santa Izabel do Pará,15.0,PA,1,4,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",3538204,Pinhalzinho,35,SP,19,M,1,3,1,1503804.0,Jacundá,15.0,PA,1,2,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",3550308,São Paulo,35,SP,17,F,1,3,1,1501402.0,Belém,15.0,PA,2,0,3,1.0,0,15567761.0,1501402.0,Belém,15.0,PA,4.0,1.0,1.0,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",3548708,São Bernardo do Campo,35,SP,19,M,1,3,1,3548708.0,São Bernardo do Campo,35.0,SP,2,0,2,1.0,0,35904958.0,3548708.0,São Bernardo do Campo,35.0,SP,2.0,1.0,1.0,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",3549409,São Joaquim da Barra,35,SP,37,M,2,1,1,3549409.0,São Joaquim da Barra,35.0,SP,1,3,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [ ]:
# Trocando NU_INSCRICAO pelo index do dataframe para evitar problemas de duplicidade de ID com números muito grandes
# Realizado nesta etapa para garantir integridade dos dados em qualquer parte futura do código

lista_nu_inscricao = np.arange(1, len(df) + 1)
df['NU_INSCRICAO'] = lista_nu_inscricao
df.head(5)

,NU_INSCRICAO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_NASCIMENTO,NO_MUNICIPIO_NASCIMENTO,CO_UF_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,1,3546801,Santa Isabel,35,SP,22,M,1,3,1,1506500.0,Santa Izabel do Pará,15.0,PA,1,4,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,2,3538204,Pinhalzinho,35,SP,19,M,1,3,1,1503804.0,Jacundá,15.0,PA,1,2,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,3,3550308,São Paulo,35,SP,17,F,1,3,1,1501402.0,Belém,15.0,PA,2,0,3,1.0,0,15567761.0,1501402.0,Belém,15.0,PA,4.0,1.0,1.0,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,4,3548708,São Bernardo do Campo,35,SP,19,M,1,3,1,3548708.0,São Bernardo do Campo,35.0,SP,2,0,2,1.0,0,35904958.0,3548708.0,São Bernardo do Campo,35.0,SP,2.0,1.0,1.0,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,5,3549409,São Joaquim da Barra,35,SP,37,M,2,1,1,3549409.0,São Joaquim da Barra,35.0,SP,1,3,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [ ]:
# Criando dataframe com colunas interessadas
enem_df = df[['NU_INSCRICAO','NO_MUNICIPIO_RESIDENCIA','SG_UF_RESIDENCIA','NU_IDADE','TP_SEXO','TP_ESTADO_CIVIL',
             'TP_COR_RACA','TP_NACIONALIDADE','TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU','TP_ESCOLA','IN_TREINEIRO','CO_ESCOLA',
             'NO_MUNICIPIO_ESC','SG_UF_ESC', 'TP_LOCALIZACAO_ESC','TP_PRESENCA_CN','TP_PRESENCA_CH',
             'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'NU_NOTA_CN','NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'TP_LINGUA', 'TP_STATUS_REDACAO',
             'NU_NOTA_COMP1', 'NU_NOTA_COMP2','NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5', 'NU_NOTA_REDACAO', 'Q025']]

In [ ]:
enem_df.shape

(813772, 33)

In [ ]:
enem_df.head(5)

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,SG_UF_ESC,TP_LOCALIZACAO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,1,Santa Isabel,SP,22,M,1,3,1,1,4,1,0,NaN,NaN,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,2,Pinhalzinho,SP,19,M,1,3,1,1,2,1,0,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,3,São Paulo,SP,17,F,1,3,1,2,0,3,0,15567761.0,Belém,PA,1.0,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,4,São Bernardo do Campo,SP,19,M,1,3,1,2,0,2,0,35904958.0,São Bernardo do Campo,SP,1.0,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,5,São Joaquim da Barra,SP,37,M,2,1,1,1,3,1,0,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

## 2. Limpeza e organização dos dados

### 2.1 Trocando nome de colunas

In [ ]:
enem_df = enem_df.rename(columns = {'NO_MUNICIPIO_RESIDENCIA':'MUNICIPIO_RESIDENCIA',
                          'SG_UF_RESIDENCIA':'UF_RESIDENCIA',
                          'NU_IDADE':'IDADE',
                          'TP_SEXO':'SEXO',
                          'TP_ESTADO_CIVIL':'ESTADO_CIVIL',
                          'TP_COR_RACA':'COR_RACA',
                          'TP_NACIONALIDADE':'NACIONALIDADE',
                          'TP_ST_CONCLUSAO':'SITUACAO_CONCLUSAO_ENSINO',
                          'TP_ESCOLA':'TIPO_ESCOLA',
                          'IN_TREINEIRO':'TREINEIRO',
                          'NO_MUNICIPIO_ESC':'MUNICIPIO_ESCOLA',
                          'SG_UF_ESC':'UF_ESCOLA',
                          'TP_LOCALIZACAO_ESC':'TIPO_LOCALIZACAO_ESCOLA',
                          'TP_PRESENCA_CN':'PRESENCA_CN',
                          'TP_PRESENCA_CH':'PRESENCA_CH',
                          'TP_PRESENCA_LC':'PRESENCA_LC',
                          'TP_PRESENCA_MT':'PRESENCA_MT',
                          'NU_NOTA_CN':'NOTA_CN',
                          'NU_NOTA_CH':'NOTA_CH',
                          'NU_NOTA_LC':'NOTA_LC',
                          'NU_NOTA_MT':'NOTA_MT',
                          'TP_LINGUA':'TIPO_LINGUA',
                          'TP_STATUS_REDACAO':'STATUS_REDACAO',
                          'NU_NOTA_COMP1':'NOTA_COMP1',
                          'NU_NOTA_COMP2':'NOTA_COMP2',
                          'NU_NOTA_COMP3':'NOTA_COMP3',
                          'NU_NOTA_COMP4':'NOTA_COMP4',
                          'NU_NOTA_COMP5':'NOTA_COMP5',
                          'NU_NOTA_REDACAO':'NOTA_REDACAO',
                          'Q025':'ACESSO_INTERNET'
                          })

In [ ]:
enem_df.head(2)

,NU_INSCRICAO,MUNICIPIO_RESIDENCIA,UF_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,COR_RACA,NACIONALIDADE,SITUACAO_CONCLUSAO_ENSINO,TP_ANO_CONCLUIU,TIPO_ESCOLA,TREINEIRO,CO_ESCOLA,MUNICIPIO_ESCOLA,UF_ESCOLA,TIPO_LOCALIZACAO_ESCOLA,PRESENCA_CN,PRESENCA_CH,PRESENCA_LC,PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TIPO_LINGUA,STATUS_REDACAO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,ACESSO_INTERNET
0,1,Santa Isabel,SP,22,M,1,3,1,1,4,1,0,NaN,NaN,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,2,Pinhalzinho,SP,19,M,1,3,1,1,2,1,0,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A

### 2.2 Verificando idade dos participantes

In [ ]:
enem_df['IDADE'].describe()

count    813772.000000
mean         20.905075
std           6.900655
min           2.000000
25%          17.000000
50%          18.000000
75%          22.000000
max          91.000000
Name: IDADE, dtype: float64

As idades mínimas e máximas apresentadas foram 2 e 91 respectivamente, considerando isto um erro, adotarei as idades mínima e máxima 15 anos e 80 anos respectivamente.

In [ ]:
enem_df = enem_df.loc[(enem_df.IDADE >= 15) & (enem_df.IDADE <= 80)]

In [ ]:
enem_df['IDADE'].describe()

count    813359.000000
mean         20.908187
std           6.897937
min          15.000000
25%          17.000000
50%          18.000000
75%          22.000000
max          80.000000
Name: IDADE, dtype: float64

### 2.3 Verificando valores não condizentes com as colunas das notas

In [ ]:
enem_df[['NOTA_CN','NOTA_CH','NOTA_LC','NOTA_MT','NOTA_REDACAO']].describe()

,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,NOTA_REDACAO
count,582300.000000,620306.000000,620306.000000,582300.000000,620306.000000
mean,4522.301668,4804.687140,4911.925227,5019.193084,587.508681
std,1532.013387,1612.050515,1562.883531,1841.646568,174.421436
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4148.000000,4486.000000,4895.000000,4316.000000,500.000000
50%,4824.000000,5228.000000,5385.000000,5195.000000,600.000000
75%,5477.000000,5771.000000,5756.000000,6241.000000,680.000000
max,8609.000000,8227.000000,8017.000000,9855.000000,1000.000000

As notas deveriam estar em um intervalo de 0 e 1000, portanto para as notas CN, CH, LC e MT será feita uma correção divindo os mesmos por 10.

In [ ]:
enem_df[['NOTA_CN','NOTA_CH','NOTA_LC','NOTA_MT']] = enem_df[['NOTA_CN','NOTA_CH','NOTA_LC','NOTA_MT']]/10

In [ ]:
enem_df[['NOTA_CN','NOTA_CH','NOTA_LC','NOTA_MT','NOTA_REDACAO']].describe()

,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,NOTA_REDACAO
count,582300.000000,620306.000000,620306.000000,582300.000000,620306.000000
mean,452.230167,480.468714,491.192523,501.919308,587.508681
std,153.201339,161.205052,156.288353,184.164657,174.421436
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,414.800000,448.600000,489.500000,431.600000,500.000000
50%,482.400000,522.800000,538.500000,519.500000,600.000000
75%,547.700000,577.100000,575.600000,624.100000,680.000000
max,860.900000,822.700000,801.700000,985.500000,1000.000000

### 2.4 Alterando valores dos dados com legenda para melhor legibilidade

* ESTADO_CIVIL
* COR_RACA
* NACIONALIDADE
* SITUACAO_CONCLUSAO_ENSINO
* TIPO_ESCOLA
* TREINEIRO
* TIPO_LOCALIZACAO_ESCOLA
* PRESENCA_CN
* PRESENCA_CH
* PRESENCA_LC
* PRESENCA_MT
* TIPO_LINGUA
* STATUS_REDACAO
* ACESSO_INTERNET

In [ ]:
# ESTADO_CIVIL
enem_df["ESTADO_CIVIL"] = enem_df["ESTADO_CIVIL"].replace({0:"Não Informado", 1:"Solteiro(a)", 2:"Casado(a)", 3:"Divorciado(a)", 4:"Viúvo(a)"})

In [ ]:
# COR_RACA
enem_df["COR_RACA"] = enem_df["COR_RACA"].replace({0:"Não Informado", 1:"Branca", 2:"Preta", 3:"Parda", 4:"Amarela", 5:"Indígena "})

In [ ]:
# NACIONALIDADE
enem_df["NACIONALIDADE"] = enem_df["NACIONALIDADE"].replace({0:"Não Informado", 1:"Brasileiro(a)", 2:"Brasileiro(a) Naturalizado(a)", 3:"Estrangeiro(a)",
                                                             4:"Brasileiro(a) Nato(a), nascido(a) no exterior"})

In [ ]:
# SITUACAO_CONCLUSAO_ENSINO
enem_df["SITUACAO_CONCLUSAO_ENSINO"] = enem_df["SITUACAO_CONCLUSAO_ENSINO"].replace({1:"Concluiu Ensino Médio", 2:"Cursando último ano do Ensino Médio",
                                                                                     3:"Cursando Ensino Médio(não último ano) ", 4:"Não concluíu e não está cursando Ensino Médio"})

In [ ]:
# TIPO_ESCOLA
enem_df["TIPO_ESCOLA"] = enem_df["TIPO_ESCOLA"].replace({1:"Não Informado", 2:"Pública", 3:"Privada", 4:"Exterior"})

In [ ]:
# TREINEIRO
enem_df["TREINEIRO"] = enem_df["TREINEIRO"].replace({0:"Não", 1:"Sim"})

In [ ]:
# TIPO_LOCALIZACAO_ESCOLA
enem_df["TIPO_LOCALIZACAO_ESCOLA"] = enem_df["TIPO_LOCALIZACAO_ESCOLA"].replace({1:"Urbana", 2:"Rural"})

In [ ]:
# PRESENCA_CN
enem_df["PRESENCA_CN"] = enem_df["PRESENCA_CN"].replace({0:"Faltou", 1:"Presente", 2:"Eliminado"})

In [ ]:
# PRESENCA_CH
enem_df["PRESENCA_CH"] = enem_df["PRESENCA_CH"].replace({0:"Faltou", 1:"Presente", 2:"Eliminado"})

In [ ]:
# PRESENCA_LC
enem_df["PRESENCA_LC"] = enem_df["PRESENCA_LC"].replace({0:"Faltou", 1:"Presente", 2:"Eliminado"})

In [ ]:
# PRESENCA_MT
enem_df["PRESENCA_MT"] = enem_df["PRESENCA_MT"].replace({0:"Faltou", 1:"Presente", 2:"Eliminado"})

In [ ]:
# TIPO_LINGUA
enem_df["TIPO_LINGUA"] = enem_df["TIPO_LINGUA"].replace({0:"Inglês", 1:"Espanhol"})

In [ ]:
# STATUS_REDACAO
# Possui erro de contagem dos índices do próprio banco de dados
enem_df["STATUS_REDACAO"] = enem_df["STATUS_REDACAO"].replace({1:"Sem problemas", 2:"Anulada", 3:"Cópia do texto motivador", 4:"Em branco",
                                                               6:"Fuga ao tema", 7:"Não atendimento ao tipo textual", 8:"Texto Insuficiente",
                                                               9:"Parte desconectada"})

In [ ]:
# ACESSO_INTERNET
enem_df["ACESSO_INTERNET"] = enem_df["ACESSO_INTERNET"].replace({"A":"Não possui", "B":"Possui"})

In [ ]:
enem_df.head(5)

,NU_INSCRICAO,MUNICIPIO_RESIDENCIA,UF_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,COR_RACA,NACIONALIDADE,SITUACAO_CONCLUSAO_ENSINO,TP_ANO_CONCLUIU,TIPO_ESCOLA,TREINEIRO,CO_ESCOLA,MUNICIPIO_ESCOLA,UF_ESCOLA,TIPO_LOCALIZACAO_ESCOLA,PRESENCA_CN,PRESENCA_CH,PRESENCA_LC,PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TIPO_LINGUA,STATUS_REDACAO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,ACESSO_INTERNET
0,1,Santa Isabel,SP,22,M,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,4,Não Informado,Não,NaN,NaN,NaN,NaN,Presente,Presente,Presente,Presente,564.6,585.8,592.9,600.2,Inglês,Sem problemas,160.0,200.0,180.0,200.0,200.0,940.0,Possui
1,2,Pinhalzinho,SP,19,M,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,2,Não Informado,Não,NaN,NaN,NaN,NaN,Faltou,Faltou,Faltou,Faltou,NaN,NaN,NaN,NaN,Espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não possui
2,3,São Paulo,SP,17,F,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Privada,Não,15567761.0,Belém,PA,Urbana,Presente,Presente,Presente,Presente,576.2,641.1,634.3,731.8,Inglês,Sem problemas,160.0,120.0,200.0,200.0,200.0,880.0,Não possui
3,4,São Bernardo do Campo,SP,19,M,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35904958.0,São Bernardo do Campo,SP,Urbana,Presente,Presente,Presente,Presente,402.2,424.8,509.6,393.2,Espanhol,Sem problemas,80.0,160.0,120.0,100.0,100.0,560.0,Possui
4,5,São Joaquim da Barra,SP,37,M,Casado(a),Branca,Brasileiro(a),Concluiu Ensino Médio,3,Não Informado,Não,NaN,NaN,NaN,NaN,Faltou,Faltou,Faltou,Faltou,NaN,NaN,NaN,NaN,Espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possui

### 2.5 Verificando se escolas possuem IDs únicos

In [ ]:
enem_df['CO_ESCOLA'] = enem_df['CO_ESCOLA'].astype(str)
combinacoes_unicas = enem_df[['CO_ESCOLA', 'TIPO_ESCOLA']].drop_duplicates().sort_values('CO_ESCOLA')

print(combinacoes_unicas)

         CO_ESCOLA    TIPO_ESCOLA
20299   11003065.0        Pública
328920  11026278.0        Pública
103317  11028483.0        Pública
147861  11033070.0        Pública
621583  11040793.0        Pública
...            ...            ...
168439  53001010.0        Pública
219354  53001036.0        Pública
123            nan        Privada
5              nan        Pública
0              nan  Não Informado

[9407 rows x 2 columns]

Existem códigos de escolas iguais com tipo_escola diferentes, como visto acima no código 35000036.0

In [ ]:
# Agrupar por 'CO_ESCOLA' e contar os valores únicos de 'TIPO_ESCOLA'
contagem_tipo_escola = enem_df.groupby('CO_ESCOLA')['TIPO_ESCOLA'].nunique()

# Encontrar o valor máximo de contagem para cada 'CO_ESCOLA'
max_contagem = contagem_tipo_escola.max()

# Encontrar a 'CO_ESCOLA' correspondente ao valor máximo de contagem
escola_max = contagem_tipo_escola.idxmax()

# Substituir o valor de 'TIPO_ESCOLA' para 'Pública' onde 'CO_ESCOLA' não corresponde ao valor máximo de contagem
enem_df.loc[enem_df['CO_ESCOLA'] != escola_max, 'TIPO_ESCOLA'] = 'Pública'
enem_df

,NU_INSCRICAO,MUNICIPIO_RESIDENCIA,UF_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,COR_RACA,NACIONALIDADE,SITUACAO_CONCLUSAO_ENSINO,TP_ANO_CONCLUIU,TIPO_ESCOLA,TREINEIRO,CO_ESCOLA,MUNICIPIO_ESCOLA,UF_ESCOLA,TIPO_LOCALIZACAO_ESCOLA,PRESENCA_CN,PRESENCA_CH,PRESENCA_LC,PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TIPO_LINGUA,STATUS_REDACAO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,ACESSO_INTERNET
0,1,Santa Isabel,SP,22,M,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,4,Não Informado,Não,nan,NaN,NaN,NaN,Presente,Presente,Presente,Presente,564.6,585.8,592.9,600.2,Inglês,Sem problemas,160.0,200.0,180.0,200.0,200.0,940.0,Possui
1,2,Pinhalzinho,SP,19,M,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,2,Não Informado,Não,nan,NaN,NaN,NaN,Faltou,Faltou,Faltou,Faltou,NaN,NaN,NaN,NaN,Espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não possui
2,3,São Paulo,SP,17,F,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,15567761.0,Belém,PA,Urbana,Presente,Presente,Presente,Presente,576.2,641.1,634.3,731.8,Inglês,Sem problemas,160.0,120.0,200.0,200.0,200.0,880.0,Não possui
3,4,São Bernardo do Campo,SP,19,M,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35904958.0,São Bernardo do Campo,SP,Urbana,Presente,Presente,Presente,Presente,402.2,424.8,509.6,393.2,Espanhol,Sem problemas,80.0,160.0,120.0,100.0,100.0,560.0,Possui
4,5,São Joaquim da Barra,SP,37,M,Casado(a),Branca,Brasileiro(a),Concluiu Ensino Médio,3,Não Informado,Não,nan,NaN,NaN,NaN,Faltou,Faltou,Faltou,Faltou,NaN,NaN,NaN,NaN,Espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possui
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813767,813768,São Paulo,SP,17,F,Solteiro(a),Preta,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35925457.0,São Paulo,SP,Urbana,Presente,Presente,Presente,Presente,367.4,455.9,499.7,43.2,Espanhol,Sem problemas,80.0,120.0,140.0,120.0,100.0,560.0,Possui
813768,813769,São Paulo,SP,17,F,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35001156.0,São Paulo,SP,Urbana,Presente,Presente,Presente,Presente,398.6,468.3,483.9,487.3,Inglês,Sem problemas,120.0,80.0,60.0,120.0,0.0,380.0,Possui
813769,813770,São Paulo,SP,17,M,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,nan,NaN,NaN,NaN,Presente,Presente,Presente,Presente,402.8,561.8,53.5,401.1,Inglês,Sem problemas,160.0,120.0,160.0,140.0,160.0,740.0,Não possui
813770,813771,Cajamar,SP,21,F,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,0,Não Informado,Não,nan,NaN,NaN,NaN,Faltou,Faltou,Faltou,Faltou,NaN,NaN,NaN,NaN,Espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possui
813771,813772,Araras,SP,18,F,Solteiro(a),Branca,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35019926.0,Araras,SP,Urbana,Presente,Presente,Presente,Presente,524.6,547.1,586.8,559.5,Inglês,Sem problemas,120.0,120.0,120.0,120.0,140.0,620.0,Possui

In [ ]:
enem_df['CO_ESCOLA'] = enem_df['CO_ESCOLA'].astype(str)
combinacoes_unicas = enem_df[['CO_ESCOLA', 'TIPO_ESCOLA']].drop_duplicates().sort_values('CO_ESCOLA')

print(combinacoes_unicas)

         CO_ESCOLA    TIPO_ESCOLA
20299   11003065.0        Pública
328920  11026278.0        Pública
103317  11028483.0        Pública
147861  11033070.0        Pública
621583  11040793.0        Pública
...            ...            ...
168439  53001010.0        Pública
219354  53001036.0        Pública
5              nan        Pública
123            nan        Privada
0              nan  Não Informado

[7027 rows x 2 columns]

## 3. Modelagem dos dados

* Trabalharemos apenas com dados de candidatos que estiveram presentes em todos os dias das provas e não foram desclassificados para evitar valores nulos ou zeros por desclassificação/falta afetando a inferência ou interpretação dos dados.

* A principal ideia será analisar resultados por categorizações e realizar comparações, bem como explorar possíveis resultados futuros baseados nos apresentados.

In [ ]:
enem_df = enem_df.query('(PRESENCA_CH == "Presente") and (PRESENCA_CN == "Presente") and (PRESENCA_LC == "Presente") and (PRESENCA_MT == "Presente")')

In [ ]:
enem_df[["NOTA_CH", "NOTA_CN", "NOTA_LC", "NOTA_MT", "NOTA_REDACAO"]].isna().sum()

NOTA_CH         0
NOTA_CN         0
NOTA_LC         0
NOTA_MT         0
NOTA_REDACAO    0
dtype: int64

In [ ]:
enem_df[['IDADE','SEXO']].isna().sum()

IDADE    0
SEXO     0
dtype: int64

### 3.1 Dropando colunas que não serão mais utilizadas

In [ ]:
enem_df.drop(columns=['PRESENCA_CH','PRESENCA_CN','PRESENCA_LC','PRESENCA_MT'], inplace=True)
enem_df.head(1)

<ipython-input-40-925d9595e866>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  enem_df.drop(columns=['PRESENCA_CH','PRESENCA_CN','PRESENCA_LC','PRESENCA_MT'], inplace=True)

,NU_INSCRICAO,MUNICIPIO_RESIDENCIA,UF_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,COR_RACA,NACIONALIDADE,SITUACAO_CONCLUSAO_ENSINO,TP_ANO_CONCLUIU,TIPO_ESCOLA,TREINEIRO,CO_ESCOLA,MUNICIPIO_ESCOLA,UF_ESCOLA,TIPO_LOCALIZACAO_ESCOLA,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TIPO_LINGUA,STATUS_REDACAO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,ACESSO_INTERNET
0,1,Santa Isabel,SP,22,M,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,4,Não Informado,Não,nan,NaN,NaN,NaN,564.6,585.8,592.9,600.2,Inglês,Sem problemas,160.0,200.0,180.0,200.0,200.0,940.0,Possui

In [ ]:
enem_df.dtypes

NU_INSCRICAO                   int64
MUNICIPIO_RESIDENCIA          object
UF_RESIDENCIA                 object
IDADE                          int64
SEXO                          object
ESTADO_CIVIL                  object
COR_RACA                      object
NACIONALIDADE                 object
SITUACAO_CONCLUSAO_ENSINO     object
TP_ANO_CONCLUIU                int64
TIPO_ESCOLA                   object
TREINEIRO                     object
CO_ESCOLA                     object
MUNICIPIO_ESCOLA              object
UF_ESCOLA                     object
TIPO_LOCALIZACAO_ESCOLA       object
NOTA_CN                      float64
NOTA_CH                      float64
NOTA_LC                      float64
NOTA_MT                      float64
TIPO_LINGUA                   object
STATUS_REDACAO                object
NOTA_COMP1                   float64
NOTA_COMP2                   float64
NOTA_COMP3                   float64
NOTA_COMP4                   float64
NOTA_COMP5                   float64
NOTA_REDACAO                 float64
ACESSO_INTERNET               object
dtype: object

In [ ]:
enem_df.isna().sum()

NU_INSCRICAO                      0
MUNICIPIO_RESIDENCIA              0
UF_RESIDENCIA                     0
IDADE                             0
SEXO                              0
ESTADO_CIVIL                      0
COR_RACA                          0
NACIONALIDADE                     0
SITUACAO_CONCLUSAO_ENSINO         0
TP_ANO_CONCLUIU                   0
TIPO_ESCOLA                       0
TREINEIRO                         0
CO_ESCOLA                         0
MUNICIPIO_ESCOLA             403994
UF_ESCOLA                    403994
TIPO_LOCALIZACAO_ESCOLA      403994
NOTA_CN                           0
NOTA_CH                           0
NOTA_LC                           0
NOTA_MT                           0
TIPO_LINGUA                       0
STATUS_REDACAO                    0
NOTA_COMP1                        0
NOTA_COMP2                        0
NOTA_COMP3                        0
NOTA_COMP4                        0
NOTA_COMP5                        0
NOTA_REDACAO                      0
ACESSO_INTERNET                   0
dtype: int64

Eliminando NaNs da base de dados, como podemos observar, elas estão apenas na classificação de localização escolar, então todos os NaNs serão substituídos por "Não Informado"

In [ ]:
enem_df = enem_df.fillna({'CO_ESCOLA':'Não Informado', 'MUNICIPIO_ESCOLA':'Não Informado', 'UF_ESCOLA':'Não Informado', 'TIPO_LOCALIZACAO_ESCOLA':'Não Informado'})

In [ ]:
enem_df.isna().sum()

NU_INSCRICAO                 0
MUNICIPIO_RESIDENCIA         0
UF_RESIDENCIA                0
IDADE                        0
SEXO                         0
ESTADO_CIVIL                 0
COR_RACA                     0
NACIONALIDADE                0
SITUACAO_CONCLUSAO_ENSINO    0
TP_ANO_CONCLUIU              0
TIPO_ESCOLA                  0
TREINEIRO                    0
CO_ESCOLA                    0
MUNICIPIO_ESCOLA             0
UF_ESCOLA                    0
TIPO_LOCALIZACAO_ESCOLA      0
NOTA_CN                      0
NOTA_CH                      0
NOTA_LC                      0
NOTA_MT                      0
TIPO_LINGUA                  0
STATUS_REDACAO               0
NOTA_COMP1                   0
NOTA_COMP2                   0
NOTA_COMP3                   0
NOTA_COMP4                   0
NOTA_COMP5                   0
NOTA_REDACAO                 0
ACESSO_INTERNET              0
dtype: int64

### 3.2 Excluíndo candidatos que registraram residência em São Paulo, mas escola fora de São Paulo.

Para evitar possíveis incoerências de análises pois estamos querendo observar relações de desempenho para escolas de São Paulo.

In [ ]:
enem_df = enem_df.query('(UF_ESCOLA == "SP") or (UF_ESCOLA == "Não Informado")')

In [ ]:
enem_df['UF_ESCOLA'].value_counts()

Não Informado    403994
SP               176655
Name: UF_ESCOLA, dtype: int64

### 3.3 Adicionando nota final

Média simples das 5 notas

In [ ]:
enem_df['MEDIA_NOTAS'] = enem_df[['NOTA_CN', 'NOTA_CH', 'NOTA_LC', 'NOTA_MT', 'NOTA_REDACAO']].mean(axis=1)
enem_df

<ipython-input-47-c6912955ed09>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  enem_df['MEDIA_NOTAS'] = enem_df[['NOTA_CN', 'NOTA_CH', 'NOTA_LC', 'NOTA_MT', 'NOTA_REDACAO']].mean(axis=1)

,NU_INSCRICAO,MUNICIPIO_RESIDENCIA,UF_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,COR_RACA,NACIONALIDADE,SITUACAO_CONCLUSAO_ENSINO,TP_ANO_CONCLUIU,TIPO_ESCOLA,TREINEIRO,CO_ESCOLA,MUNICIPIO_ESCOLA,UF_ESCOLA,TIPO_LOCALIZACAO_ESCOLA,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TIPO_LINGUA,STATUS_REDACAO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,ACESSO_INTERNET,MEDIA_NOTAS
0,1,Santa Isabel,SP,22,M,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,4,Não Informado,Não,nan,Não Informado,Não Informado,Não Informado,564.6,585.8,592.9,600.2,Inglês,Sem problemas,160.0,200.0,180.0,200.0,200.0,940.0,Possui,656.70
3,4,São Bernardo do Campo,SP,19,M,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35904958.0,São Bernardo do Campo,SP,Urbana,402.2,424.8,509.6,393.2,Espanhol,Sem problemas,80.0,160.0,120.0,100.0,100.0,560.0,Possui,457.96
5,6,Embu-Guaçu,SP,17,F,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,nan,Não Informado,Não Informado,Não Informado,399.6,426.8,487.2,419.2,Inglês,Sem problemas,120.0,120.0,120.0,120.0,80.0,560.0,Possui,458.56
8,9,Guarulhos,SP,23,F,Solteiro(a),Branca,Brasileiro(a),Concluiu Ensino Médio,5,Não Informado,Não,nan,Não Informado,Não Informado,Não Informado,625.7,646.5,629.3,796.1,Inglês,Sem problemas,160.0,200.0,180.0,180.0,160.0,880.0,Possui,715.52
10,11,São José do Rio Preto,SP,18,F,Solteiro(a),Branca,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35028927.0,São José do Rio Preto,SP,Urbana,449.5,533.3,555.9,612.8,Espanhol,Sem problemas,120.0,160.0,120.0,80.0,100.0,580.0,Não possui,546.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813766,813767,São Paulo,SP,18,F,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,1,Não Informado,Não,nan,Não Informado,Não Informado,Não Informado,417.8,394.3,52.7,479.1,Espanhol,Sem problemas,100.0,120.0,120.0,140.0,100.0,580.0,Possui,384.78
813767,813768,São Paulo,SP,17,F,Solteiro(a),Preta,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35925457.0,São Paulo,SP,Urbana,367.4,455.9,499.7,43.2,Espanhol,Sem problemas,80.0,120.0,140.0,120.0,100.0,560.0,Possui,385.24
813768,813769,São Paulo,SP,17,F,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35001156.0,São Paulo,SP,Urbana,398.6,468.3,483.9,487.3,Inglês,Sem problemas,120.0,80.0,60.0,120.0,0.0,380.0,Possui,443.62
813769,813770,São Paulo,SP,17,M,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,nan,Não Informado,Não Informado,Não Informado,402.8,561.8,53.5,401.1,Inglês,Sem problemas,160.0,120.0,160.0,140.0,160.0,740.0,Não possui,431.84
813771,813772,Araras,SP,18,F,Solteiro(a),Branca,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35019926.0,Araras,SP,Urbana,524.6,547.1,586.8,559.5,Inglês,Sem problemas,120.0,120.0,120.0,120.0,140.0,620.0,Possui,567.60

In [ ]:
# Adicionando faixa de notas
faixas = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
rotulos = ['0-100', '101-200', '201-300', '301-400', '401-500', '501-600', '601-700', '701-800', '801-900', '901-1000']

enem_df['FAIXA_MEDIA_NOTAS'] = pd.cut(enem_df['MEDIA_NOTAS'], bins=faixas, labels=rotulos, right=False)

In [ ]:
enem_df

,NU_INSCRICAO,MUNICIPIO_RESIDENCIA,UF_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,COR_RACA,NACIONALIDADE,SITUACAO_CONCLUSAO_ENSINO,TP_ANO_CONCLUIU,TIPO_ESCOLA,TREINEIRO,CO_ESCOLA,MUNICIPIO_ESCOLA,UF_ESCOLA,TIPO_LOCALIZACAO_ESCOLA,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,TIPO_LINGUA,STATUS_REDACAO,NOTA_COMP1,NOTA_COMP2,NOTA_COMP3,NOTA_COMP4,NOTA_COMP5,NOTA_REDACAO,ACESSO_INTERNET,MEDIA_NOTAS,FAIXA_MEDIA_NOTAS
0,1,Santa Isabel,SP,22,M,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,4,Não Informado,Não,nan,Não Informado,Não Informado,Não Informado,564.6,585.8,592.9,600.2,Inglês,Sem problemas,160.0,200.0,180.0,200.0,200.0,940.0,Possui,656.70,601-700
3,4,São Bernardo do Campo,SP,19,M,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35904958.0,São Bernardo do Campo,SP,Urbana,402.2,424.8,509.6,393.2,Espanhol,Sem problemas,80.0,160.0,120.0,100.0,100.0,560.0,Possui,457.96,401-500
5,6,Embu-Guaçu,SP,17,F,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,nan,Não Informado,Não Informado,Não Informado,399.6,426.8,487.2,419.2,Inglês,Sem problemas,120.0,120.0,120.0,120.0,80.0,560.0,Possui,458.56,401-500
8,9,Guarulhos,SP,23,F,Solteiro(a),Branca,Brasileiro(a),Concluiu Ensino Médio,5,Não Informado,Não,nan,Não Informado,Não Informado,Não Informado,625.7,646.5,629.3,796.1,Inglês,Sem problemas,160.0,200.0,180.0,180.0,160.0,880.0,Possui,715.52,701-800
10,11,São José do Rio Preto,SP,18,F,Solteiro(a),Branca,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35028927.0,São José do Rio Preto,SP,Urbana,449.5,533.3,555.9,612.8,Espanhol,Sem problemas,120.0,160.0,120.0,80.0,100.0,580.0,Não possui,546.30,501-600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813766,813767,São Paulo,SP,18,F,Solteiro(a),Parda,Brasileiro(a),Concluiu Ensino Médio,1,Não Informado,Não,nan,Não Informado,Não Informado,Não Informado,417.8,394.3,52.7,479.1,Espanhol,Sem problemas,100.0,120.0,120.0,140.0,100.0,580.0,Possui,384.78,301-400
813767,813768,São Paulo,SP,17,F,Solteiro(a),Preta,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35925457.0,São Paulo,SP,Urbana,367.4,455.9,499.7,43.2,Espanhol,Sem problemas,80.0,120.0,140.0,120.0,100.0,560.0,Possui,385.24,301-400
813768,813769,São Paulo,SP,17,F,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35001156.0,São Paulo,SP,Urbana,398.6,468.3,483.9,487.3,Inglês,Sem problemas,120.0,80.0,60.0,120.0,0.0,380.0,Possui,443.62,401-500
813769,813770,São Paulo,SP,17,M,Solteiro(a),Parda,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,nan,Não Informado,Não Informado,Não Informado,402.8,561.8,53.5,401.1,Inglês,Sem problemas,160.0,120.0,160.0,140.0,160.0,740.0,Não possui,431.84,401-500
813771,813772,Araras,SP,18,F,Solteiro(a),Branca,Brasileiro(a),Cursando último ano do Ensino Médio,0,Pública,Não,35019926.0,Araras,SP,Urbana,524.6,547.1,586.8,559.5,Inglês,Sem problemas,120.0,120.0,120.0,120.0,140.0,620.0,Possui,567.60,501-600

## 4. Salvando dados tratados em um novo arquivo

In [ ]:
enem_df.to_csv('/content/drive/MyDrive/Portfolio - Data Analysis | BI/ENEM SP 2019 Performance/enem_sp_2019_treated.csv', index=False)

In [ ]:
# primeiras_200_linhas = enem_df.head(200)
# primeiras_200_linhas.to_excel('/content/drive/MyDrive/Portfolio - Data Analysis | BI/ENEM SP 2019 Performance/enem_sp_2019_treated.xlsx', index=False)

# enem_df.to_excel('/content/drive/MyDrive/Portfolio - Data Analysis | BI/ENEM SP 2019 Performance/enem_sp_2019_treated.xlsx', index=False)